//! ModelRegistryClient trait and model registry implementations.

use std::fmt::Write as _;

use async_trait::async_trait;

use crate::config::ModelSchemaConfig;

pub mod mlflow;

/// A model artifact fetched from the registry.
#[derive(Debug)]
pub struct RegisteredModel {
    pub name: String,
    pub version: String,
    /// Local filesystem path to the downloaded ONNX artifact.
    pub local_path: String,
}

/// Subset of config values populated from the model registry during `axon init`.
///
/// All fields are optional because registries vary in what they store.
/// Fields absent from the registry are `None` and appear as TODO placeholders
/// in the generated config.
#[derive(Debug, Default)]
pub struct ConfigSeed {
    /// Input and output tensor specs, derived from the model signature if available.
    pub model_schema: Option<ModelSchemaConfig>,
    pub mean: Option<f32>,
    pub std: Option<f32>,
    pub clip_min: Option<f32>,
    pub clip_max: Option<f32>,
    pub threshold: Option<f32>,
}

#[allow(clippy::unwrap_used)] // writeln! to String is infallible; Write::write_str always returns Ok
impl ConfigSeed {
    /// Generates a starter config.toml string from the seed values.
    ///
    /// Present fields are written with their values; absent fields appear as
    /// TODO placeholders.
    pub fn generate_config(&self, model_name: &str, model_version: &str) -> String {
        let mut out = String::new();

        writeln!(
            out,
            "# Generated by axon init. Fill in all TODO values before starting axon."
        )
        .unwrap();
        writeln!(out).unwrap();

        writeln!(out, "[grpc]").unwrap();
        writeln!(out, "host = \"0.0.0.0\"").unwrap();
        writeln!(out, "port = 50051").unwrap();
        writeln!(out, "stream_poll_interval_ms = 1").unwrap();
        writeln!(out, "request_timeout_ms = 5000").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "[backend]").unwrap();
        writeln!(out, "type = \"onnx_runtime\"").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "[registry]").unwrap();
        writeln!(out, "type = \"mlflow\"").unwrap();
        writeln!(
            out,
            "uri = \"TODO: MLflow tracking server URI (e.g. http://localhost:5000)\""
        )
        .unwrap();
        writeln!(out, "model_name = \"{model_name}\"").unwrap();
        writeln!(out, "model_version = \"{model_version}\"").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "[store]").unwrap();
        writeln!(out, "type = \"redis\"").unwrap();
        writeln!(out, "host = \"localhost\"").unwrap();
        writeln!(out, "port = 6379").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "[metrics]").unwrap();
        writeln!(out, "port = 9090").unwrap();
        writeln!(out).unwrap();

        self.write_model_schema(&mut out);
        self.write_pipeline_stages(&mut out);

        out
    }

    fn write_model_schema(&self, out: &mut String) {
        match &self.model_schema {
            Some(schema) => {
                for input in &schema.inputs {
                    writeln!(out, "[[model_schema.inputs]]").unwrap();
                    writeln!(out, "name  = \"{}\"", input.name).unwrap();
                    writeln!(out, "dtype = \"{}\"", input.dtype).unwrap();
                    let shape = input
                        .shape
                        .iter()
                        .map(|d| d.to_string())
                        .collect::<Vec<_>>()
                        .join(", ");
                    writeln!(out, "shape = [{shape}]").unwrap();
                    writeln!(out).unwrap();
                }
                for output in &schema.outputs {
                    writeln!(out, "[[model_schema.outputs]]").unwrap();
                    writeln!(out, "name  = \"{}\"", output.name).unwrap();
                    writeln!(out, "dtype = \"{}\"", output.dtype).unwrap();
                    let shape = output
                        .shape
                        .iter()
                        .map(|d| d.to_string())
                        .collect::<Vec<_>>()
                        .join(", ");
                    writeln!(out, "shape = [{shape}]").unwrap();
                    writeln!(out).unwrap();
                }
            }
            None => {
                writeln!(out, "# TODO: fill in model input tensor spec").unwrap();
                writeln!(out, "[[model_schema.inputs]]").unwrap();
                writeln!(out, "name  = \"TODO\"").unwrap();
                writeln!(out, "dtype = \"float32\"").unwrap();
                writeln!(out, "shape = [1, TODO]").unwrap();
                writeln!(out).unwrap();
                writeln!(out, "# TODO: fill in model output tensor spec").unwrap();
                writeln!(out, "[[model_schema.outputs]]").unwrap();
                writeln!(out, "name  = \"TODO\"").unwrap();
                writeln!(out, "dtype = \"float32\"").unwrap();
                writeln!(out, "shape = [1, 1]").unwrap();
                writeln!(out).unwrap();
            }
        }
    }

    fn write_pipeline_stages(&self, out: &mut String) {
        // Impute before validate so NaNs are replaced before shape checking.
        writeln!(out, "[[pipeline.stages]]").unwrap();
        writeln!(out, "type          = \"impute\"").unwrap();
        writeln!(out, "default_value = 0.0").unwrap();
        writeln!(out).unwrap();

        if self.clip_min.is_some() || self.clip_max.is_some() {
            writeln!(out, "[[pipeline.stages]]").unwrap();
            writeln!(out, "type = \"clip\"").unwrap();
            match self.clip_min {
                Some(v) => writeln!(out, "min  = {v}").unwrap(),
                None => writeln!(out, "min  = TODO").unwrap(),
            }
            match self.clip_max {
                Some(v) => writeln!(out, "max  = {v}").unwrap(),
                None => writeln!(out, "max  = TODO").unwrap(),
            }
            writeln!(out).unwrap();
        }

        writeln!(out, "[[pipeline.stages]]").unwrap();
        writeln!(out, "type = \"normalize\"").unwrap();
        match self.mean {
            Some(v) => writeln!(out, "mean = {v}").unwrap(),
            None => writeln!(out, "mean = TODO").unwrap(),
        }
        match self.std {
            Some(v) => writeln!(out, "std  = {v}").unwrap(),
            None => writeln!(out, "std  = TODO").unwrap(),
        }
        writeln!(out).unwrap();

        writeln!(out, "[[pipeline.stages]]").unwrap();
        writeln!(out, "type = \"infer\"").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "[[pipeline.stages]]").unwrap();
        writeln!(out, "type        = \"postprocess\"").unwrap();
        match self.threshold {
            Some(v) => writeln!(out, "threshold   = {v}").unwrap(),
            None => writeln!(out, "threshold   = TODO").unwrap(),
        }
        writeln!(
            out,
            "output_type = \"binary\"  # binary | probability | raw"
        )
        .unwrap();
    }
}

#[async_trait]
pub trait ModelRegistryClient: std::fmt::Debug + Send + Sync {
    /// Fetches the model artifact and downloads it to a local path.
    ///
    /// # Implementors
    ///
    /// **Thread safety:** may be called concurrently from multiple async tasks;
    /// `&self` must be safe to share across task boundaries.
    ///
    /// **Output contract:** on success, [`RegisteredModel::local_path`] must
    /// point to an existing, readable ONNX file. The file must remain stable
    /// for the lifetime of the process; the caller does not re-fetch between
    /// requests.
    ///
    /// **Error contract:** return [`crate::error::RegistryError::ModelNotFound`]
    /// if the (name, version) pair does not exist,
    /// [`crate::error::RegistryError::Request`] for network failures, or
    /// [`crate::error::RegistryError::Io`] if writing the artifact to disk
    /// fails.
    ///
    /// **Idempotency:** safe to call multiple times with the same arguments.
    /// Re-downloading may overwrite the local file with identical content.
    async fn fetch_model(
        &self,
        name: &str,
        version: &str,
    ) -> Result<RegisteredModel, crate::error::RegistryError>;

    /// Fetches model signature and logged params to seed a starter config.
    async fn fetch_config_seed(
        &self,
        name: &str,
        version: &str,
    ) -> Result<ConfigSeed, crate::error::RegistryError>;
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{ModelSchemaConfig, TensorSpec};

    #[test]
    fn empty_seed_has_todos_and_fixed_structure() {
        let seed = ConfigSeed::default();
        let out = seed.generate_config("my-model", "3");
        assert!(out.contains("my-model"));
        assert!(out.contains("\"3\""));
        assert!(out.contains("TODO"));
        assert!(out.contains("[grpc]"));
        assert!(out.contains("[backend]"));
        assert!(out.contains("[registry]"));
        assert!(out.contains("[store]"));
        assert!(out.contains("[metrics]"));
        assert!(out.contains("[[pipeline.stages]]"));
    }

    #[test]
    fn no_clip_stage_when_bounds_absent() {
        let out = ConfigSeed::default().generate_config("m", "1");
        assert!(!out.contains("type = \"clip\""));
    }

    #[test]
    fn clip_stage_emitted_when_clip_min_set() {
        let seed = ConfigSeed {
            clip_min: Some(-1.0),
            ..Default::default()
        };
        assert!(seed.generate_config("m", "1").contains("type = \"clip\""));
    }

    #[test]
    fn clip_stage_emitted_when_clip_max_set() {
        let seed = ConfigSeed {
            clip_max: Some(1.0),
            ..Default::default()
        };
        assert!(seed.generate_config("m", "1").contains("type = \"clip\""));
    }

    #[test]
    fn full_seed_writes_all_values() {
        let seed = ConfigSeed {
            model_schema: Some(ModelSchemaConfig {
                inputs: vec![TensorSpec {
                    name: "features".to_owned(),
                    dtype: "float32".to_owned(),
                    shape: vec![1, 64],
                }],
                outputs: vec![TensorSpec {
                    name: "score".to_owned(),
                    dtype: "float32".to_owned(),
                    shape: vec![1, 1],
                }],
            }),
            mean: Some(0.5),
            std: Some(1.5),
            clip_min: Some(-3.0),
            clip_max: Some(3.0),
            threshold: Some(0.8),
        };
        let out = seed.generate_config("fraud", "7");
        assert!(out.contains("fraud"));
        assert!(out.contains("type = \"clip\""));
        assert!(out.contains("mean = 0.5"));
        assert!(out.contains("std  = 1.5"));
        assert!(out.contains("threshold   = 0.8"));
        assert!(out.contains("features"));
        assert!(out.contains("score"));
        assert!(!out.contains("name  = \"TODO\""));
    }

    #[test]
    fn required_pipeline_stages_always_present() {
        let out = ConfigSeed::default().generate_config("m", "1");
        assert!(out.contains("type          = \"impute\""));
        assert!(out.contains("type = \"normalize\""));
        assert!(out.contains("type = \"infer\""));
        assert!(out.contains("type        = \"postprocess\""));
    }

    #[test]
    fn partial_clip_uses_todo_for_missing_bound() {
        let seed = ConfigSeed {
            clip_min: Some(-5.0),
            ..Default::default()
        };
        let out = seed.generate_config("m", "1");
        assert!(out.contains("type = \"clip\""));
        assert!(out.contains("max  = TODO"));
    }
}
